### PR TITLE
Changing i18n resources files from toml to json.

### PR DESCRIPTION
**Pull request by rlemaire**
Changing i18n resources files from toml to json to resolve issue #6.

### CODE REVIEW

**Comment by yaaax** [comment]
Une raison d'avoir choisi JSON ?
Cf. https://www.lucidchart.com/techblog/2018/07/16/why-json-isnt-a-good-configuration-language/

**Comment by rlemaire** [comment]
Il y en avait une mais je ne me souviens plus laquelle j'avoue.

**Comment by AwebsomeFr** [comment]
I had suggested it. I thought that was a good idea :s.

**Comment by yaaax** [comment]
No big drama here :)

If it's still time to change, let's keep the widely adopted TOML in Hugo community?
(see table 2 here : https://freecontent.manning.com/using-markup-languages-with-hugo/)

**Comment by AwebsomeFr** [comment]
Changement made (see [PR20](https://github.com/cnumr/EcoIndex/pull/20).

**Pull request closed without merging**
