### PR TITLE
Remove URL field type to accept uncomplete URL

### PR DESCRIPTION
**Pull request by JulienWilhelm**
Resolve issue #200 ?

URL tested with success : 
- google.com
- http://google.com
- www.google.com
- https://www.google.com

### CODE REVIEW

**Comment by JulienWilhelm** [comment]
But... On local, we are using the API, no? And this is seems to work. 
JS works before that we send the final value (a valid URL) to the API.
Am I missing something?

**Comment by vvatelot** [comment]
My Bad ! You're right !
The Logic is already implemented https://github.com/cnumr/EcoIndex/blob/25c8b3ad9fd7f93bcae0b7292c36ef85c9653889/assets/js/services/AnalysisService.js#L13
So yes, it works

**Comment by JulienWilhelm** [comment]
Great! Merge?

**Review by vvatelot — APPROVED** [review]

**Comment by vvatelot** [comment]
Go ! I let you the honor !

**Pull request merged**
